@startuml entity-relationship


package "User Things" {
    entity "User" {
      +id : uuid
      --
      password : string
      authToken : string
      nombre : string
      email : string
    }

    entity "UserConfig" {
        +userId : uuid <<FK>>
        +mailNotifications: bool
        +smsNotifications: bool
    }
}

package "Group Things"{
    entity "Group" {
    +id: uuid
    ---
    name: string
    description: string
    ownerId: uuid <<FK>>
    mainCurrencyId: uuid <<FK>>
    }
    entity "GroupConfig"{
        +groupId: uuid <<FK>>
        ---
        approvalRule: int
        expenseLimit: int
        isPrivate: bool
    }
}

entity "Friend"{
    +user1Id: uuid <<FK>>
    +user2Id: uuid <<FK>>
}
'chequeos de que el que invita sea admin del grupo'
'que el nuevo miembro no sea parte del grupo'
entity "NewMemberProposal"{
    NewMemberProposalId: uuid
    ---
    newMemberId: uuid <<FK>>
    groupId: uuid <<FK>>
    adminId: uuid <<FK>>
    status: uuid <<FK>>
}

entity "Wallet"{
    +address: string
    'Solo uno de los id puede tener valor el otro seria nulo'
    +userId:  uuid <<FK>>
    +groupId: uuid <<FK>>
    ---
    balance: uint256
    currencyId: uuid <<FK>>
}



entity "Transaction" {
    +id : uuid
    ---
    amount: uint256
' If negative -> withdraw, else -> deposit
    userId: uuid <<FK>>
    groupId: uuid <<FK>>
    description: string
}

entity "Currency" {
    +id: uuid
    ---
    priceApi: string
    name: string
    ticker: string
}
entity "UserInGroup"{
    +userId: uuid <<FK>>
    +groupId: uuid <<FK>>
    ---
    balance: float
    isAdmin: bool
}

entity "Expense" {
    +id: uuid
    ---
    fromUserId: uuid <<FK>>
    currencyId: uuid <<FK>>
    groupId: uuid <<FK>>
    description: string
    amount: uint256
    status: uuid <<FK>>
    
}

entity "Status"{
    'Podrían ser PENDING, APPROVED, REJECTED'
    +id: uuid
    description: String
}


User ||--|| UserConfig : Has config
User ||--o{ Expense : Makes

User ||--o{ UserInGroup
Group ||--o{ UserInGroup


Currency ||--o{ Expense: Has $
Group ||--o{ Expense : Generates
Currency ||--o{ Group : Has main currency

Currency ||--o{ Wallet: Has $
User ||--|| Wallet
Group ||--|| Wallet

Currency ||--o{ Transaction: Has $
Group ||--o{ Transaction : Generates
User ||--o{ Transaction : Makes

User ||--o{ Friend
Group ||--|| GroupConfig: Has config

Expense }o--|| Status: has a status of

User ||--o{ NewMemberProposal
Group ||--o{ NewMemberProposal

@enduml